<<<<<<< HEAD
# Generated by Django 5.0.7 on 2024-08-10 07:33
=======
# Generated by Django 5.0.7 on 2024-08-07 04:47
>>>>>>> b958a7abe557a46e3e3c3f2f9128024980177d69

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_post_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='post_images/'),
        ),
    ]
