# Generated by Django 5.0.7 on 2024-09-07 07:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='video',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='post_images/'),
            preserve_default=False,
        ),
    ]
